# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

test: &test
  steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-test-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}-{{ checksum ".circleci/config.yml" }}
          # fallback to using the latest cache if no exact match is found
          - v2-test-dependencies-

      # php:* has no zip extension and the CLI is faster to install.
      - run: sudo apt-get update -y && sudo apt-get install unzip -y

      - run: |
          EXPECTED_SIGNATURE=$(curl -L https://composer.github.io/installer.sig)
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")

          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
          then
              >&2 echo 'ERROR: Invalid installer signature'
              rm composer-setup.php
              exit 1
          fi

          php composer-setup.php --quiet --install-dir $HOME/.local/bin --filename composer

      - run: composer update -n --prefer-dist $COMPOSER_FLAGS

      - save_cache:
          paths:
            - $HOME/.composer/cache/files
          key: v2-test-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}-{{ checksum ".circleci/config.yml" }}

      # run tests!
      - run: |
          mkdir -p build/logs
          vendor/bin/phpunit --testsuite Unit

      - store_test_results:
          path: build/logs

test_and_cover: &test_and_cover
  steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-test-cover-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}-{{ checksum ".circleci/config.yml" }}
          # fallback to using the latest cache if no exact match is found
          - v2-test-cover-dependencies-

      # php:* has no zip extension and the CLI is faster to install.
      - run: sudo apt-get update -y && sudo apt-get install unzip -y

      - run: |
          EXPECTED_SIGNATURE=$(curl -L https://composer.github.io/installer.sig)
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")

          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
          then
              >&2 echo 'ERROR: Invalid installer signature'
              rm composer-setup.php
              exit 1
          fi

          php composer-setup.php --quiet --install-dir $HOME/.local/bin --filename composer

      - run: composer update -n --prefer-dist

      - run: |
          [ -f /usr/local/lib/php/extensions/no-debug-non-zts-20170718/xdebug.so ] || sudo pecl install xdebug
          sudo echo 'zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20170718/xdebug.so' > /usr/local/etc/php/conf.d/xdebug.ini
          sudo echo 'xdebug.mode=coverage' >> /usr/local/etc/php/conf.d/xdebug.ini

      - save_cache:
          paths:
            - $HOME/.composer/cache/files
            - /usr/local/lib/php/extensions/no-debug-non-zts-20170718
            - /usr/local/etc/php/conf.d/xdebug.ini

          key: v2-test-cover-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}-{{ checksum ".circleci/config.yml" }}

      # run tests!
      - run: |
          mkdir -p build/logs
          vendor/bin/phpunit --testsuite Unit

      - store_test_results:
          path: build/logs

code_fixer: &code_fixer
  steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-test-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}-{{ checksum ".circleci/config.yml" }}
          # fallback to using the latest cache if no exact match is found
          - v2-test-dependencies-

      # php:* has no zip extension and the CLI is faster to install.
      - run: sudo apt-get update -y && sudo apt-get install unzip -y

      - run: |
          EXPECTED_SIGNATURE=$(curl -L https://composer.github.io/installer.sig)
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")

          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
          then
              >&2 echo 'ERROR: Invalid installer signature'
              rm composer-setup.php
              exit 1
          fi

          php composer-setup.php --quiet --install-dir $HOME/.local/bin --filename composer

      - run: composer update -n --prefer-dist

      - save_cache:
          paths:
            - $HOME/.composer/cache/files
          key: v2-test-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}-{{ checksum ".circleci/config.yml" }}

      # run tests!
      - run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php -v --dry-run --using-cache=no --path-mode=intersection -- src tests

tag_release: &tag_release
  steps:
      - run: |
          # Decrypt the git_deploy_key.enc key into /tmp/git_deploy_key
          openssl aes-256-cbc -d -K $REPO_ENC_KEY -iv $REPO_ENC_IV -in git_deploy_key.enc -out /tmp/git_deploy_key
          # Make sure only the current user can read the private key
          chmod 600 /tmp/git_deploy_key
          # Create a script to return the passphrase environment variable to ssh-add
          echo 'echo ${SSL_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
          # Start the authentication agent
          eval "$(ssh-agent -s)"
          # Add the key to the authentication agent
          DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
      - run: npx semantic-release

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/php:8.2

    working_directory: ~/repo

    <<: *test_and_cover

  build_php81:
    docker:
      - image: cimg/php:8.1

    working_directory: ~/repo

    environment:
      - COMPOSER_FLAGS: --prefer-lowest

    <<: *test

  code_fixer:
    docker:
      - image: cimg/php:8.2

    working_directory: ~/repo

    environment:
      - PHP_CS_FIXER_IGNORE_ENV: 1

    <<: *code_fixer

  release:
    docker:
      - image: cimg/node
    <<: *tag_release

workflows:
  version: 2

  # Declare a workflow that runs all of our jobs in parallel.
  test_cover_workflow:
    jobs:
      - build
      - build_php81
      - code_fixer
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - /^[0-9]+\.x/

  weekly:
    triggers:
      - schedule:
          # Run jobs every Monday morning at 12AM
          cron: "0 0 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
      - build_php81
      - code_fixer
